import html from '../../assets/skills/html.png'
import css from '../../assets/skills/css.png'
import js from '../../assets/skills/javascript.png'
import reactjs from '../../assets/skills/react.jpeg'
import tailwindcss from '../../assets/skills/tailwind.jpeg'
import bootstrap from '../../assets/skills/bootstrap.png'
import jquery from '../../assets/skills/jquery.png'
import firebase from '../../assets/skills/firebase.png'
import mongodb from '../../assets/skills/mongodb.png'
import git from '../../assets/skills/git.jpg'
import github from '../../assets/skills/github.png'
import c from '../../assets/skills/c.png'
import cpp from '../../assets/skills/cpp.jpg'
import uiux from '../../assets/skills/uiux.jpg'
import figma from '../../assets/skills/figma.png'
import nextjs from '../../assets/skills/nextjs.svg'
import ts from '../../assets/skills/typescript.jpg'

export  {html, css, js, reactjs, tailwindcss,bootstrap, jquery, firebase, mongodb, git, github, c, cpp, uiux, figma, nextjs, ts}